from __future__ import annotations

from pathlib import Path


class KpointsValidator:
    @staticmethod
    def parse_kpoints(kpoints_path: str | Path) -> dict[str, any] | None:
        path = Path(kpoints_path)
        if not path.exists():
            return None

        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                lines = [line.strip() for line in f if line.strip()]

            if len(lines) < 4:
                return None

            # Line 1: Comment
            comment = lines[0]
            # Line 2: Number of k-points (usually 0 for automatic generation)
            num_kpoints = int(lines[1])
            # Line 3: Mesh type (Gamma/Monkhorst-Pack)
            mesh_type = lines[2].lower()
            
            # Line 4: Mesh dimensions (3 integers)
            mesh_dims = [int(x) for x in lines[3].split()[:3]]
            
            if len(mesh_dims) < 3:
                return None

            return {
                "comment": comment,
                "num_kpoints": num_kpoints,
                "type": "gamma" if mesh_type.startswith("g") else "monkhorst-pack",
                "mesh": tuple(mesh_dims)
            }
        except Exception:
            return None

    @staticmethod
    def validate(kpoints_path: str | Path, lattice_lengths: tuple[float, float, float]) -> dict[str, any]:
        path = Path(kpoints_path)
        if not path.exists():
            return {
                "valid": False,
                "warnings": ["Arquivo KPOINTS nao encontrado."],
                "suggested_mesh": (1, 1, 1),
                "mesh_details": {}
            }

        k_data = KpointsValidator.parse_kpoints(path)
        if not k_data:
            return {
                "valid": False,
                "warnings": ["Erro ao processar o formato do arquivo KPOINTS."],
                "suggested_mesh": (1, 1, 1),
                "mesh_details": {}
            }

        a, b, c = lattice_lengths
        nx, ny, nz = k_data["mesh"]
        
        # Calculate densities (Nx * length)
        ka = nx * a
        kb = ny * b
        kc = nz * c

        warnings = []
        
        # Optimal mesh suggestions: Target density ~35 Angstroms
        sug_nx = max(1, round(35.0 / a)) if a > 0 else 1
        sug_ny = max(1, round(35.0 / b)) if b > 0 else 1
        sug_nz = max(1, round(35.0 / c)) if c > 0 else 1
        suggested_mesh = (sug_nx, sug_ny, sug_nz)

        directions = [("X", ka, a, nx, sug_nx), ("Y", kb, b, ny, sug_ny), ("Z", kc, c, nz, sug_nz)]
        for name, k_dens, length, n_curr, n_sug in directions:
            if length <= 0:
                continue
            if k_dens < 25.0:
                warnings.append(
                    f"Malha na direcao {name} ({n_curr}x{length:.2f} = {k_dens:.2f} A) e insuficiente (recomendado > 25 A). Sugestao: {n_sug}."
                )
            elif k_dens > 50.0:
                warnings.append(
                    f"Malha na direcao {name} ({n_curr}x{length:.2f} = {k_dens:.2f} A) e sobredensa (recomendado < 50 A), podendo atrasar o calculo. Sugestao: {n_sug}."
                )

        return {
            "valid": len(warnings) == 0,
            "warnings": warnings,
            "suggested_mesh": suggested_mesh,
            "mesh_details": {
                "type": k_data["type"],
                "mesh": [nx, ny, nz],
                "densities": [round(ka, 2), round(kb, 2), round(kc, 2)]
            }
        }

    @staticmethod
    def generate_kpoints(kpoints_path: str | Path, mesh: tuple[int, int, int]) -> dict[str, any]:
        path = Path(kpoints_path)
        nx, ny, nz = mesh
        
        backup_path = None
        if path.exists():
            import shutil
            backup_path = path.with_suffix(".kpoints.bak")
            shutil.copy2(path, backup_path)
            
        try:
            content = f"Automatic mesh generated by VASP Workflow Assistant\n0\nMonkhorst-Pack\n{nx} {ny} {nz}\n0 0 0\n"
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
                
            return {
                "success": True,
                "backup": backup_path.name if backup_path else None
            }
        except Exception as e:
            if backup_path and backup_path.exists():
                import shutil
                shutil.copy2(backup_path, path)
            return {"success": False, "error": str(e)}
